### PR TITLE
Bump Python 3.6.

### PR DESCRIPTION
**Pull request by dlorenc**

### CODE REVIEW

**Comment by dlorenc** [comment]
cc @sharifelgamal

**Comment by liyanhui1228** [comment]
We will also need to update the tests in [here](https://github.com/GoogleCloudPlatform/python-runtime/blob/master/tests/virtualenv/virtualenv_python36.yaml#L28) and [here](https://github.com/GoogleCloudPlatform/python-runtime/blob/master/tests/no-virtualenv/no-virtualenv.yaml#L46).

**Comment by dlorenc** [comment]
> We will also need to update the tests in here and here.

Ah thanks, so this PR is just meant to update the interpreter builder (which is now decoupled from the runtime builds). After this goes in, I'll run the job to publish new interpreters to GCS, then send another PR to rebuild the runtime image itself and bump that test (it'll fail until I do it in this order I think).

**Comment by liyanhui1228** [comment]
Thanks! That sounds good!

**Pull request merged**
