### PR TITLE
adding license tests to structure tests

### PR DESCRIPTION
**Pull request by sharifelgamal**

### CODE REVIEW

**Comment by jonparrott** [comment]
What's this do?

**Comment by sharifelgamal** [comment]
Automated tests to check that all packages installed in the image conform to Google's open source licensing stardards. Check out https://github.com/GoogleCloudPlatform/runtimes-common/blob/master/structure_tests/licenses_test.go (and the corresponding README) for more details.

**Comment by duggelz** [comment]
Thanks for the pointer, this was pretty mysterious.  Maybe a link or something in the license.yaml file?

Can you also update the `structure_test` target in `tests/Makefile`?

**Comment by sharifelgamal** [comment]
Done

**Pull request merged**
